### ISSUE TITLE
getting X at the background instead of a nice frame

### ISSUE THREAD

**Issue by Tsabary** [anonymous-ME/TagsEditText#1]
After approving a tag, it appears as there is an X at it's background instead of it being inside a nice frame. Not sure how to edit it.
Also, how do I  access the keyboard when sending the form. This is probably an obvious answer to many but I am a bit confused by that. Are they stored in an array? They are separate strings, so how do I call each?

**Comment by anonymous-ME** [comment]
[Resolved.](https://github.com/anonymous-ME/TagsEditText/commit/bb0c748a935d9f4bd8a6998a06ab42f936628cbd)
